### ISSUE TITLE
Erroneous visualisation of linear trend on graphs - Kam-Ol

### ISSUE THREAD

**Issue by KateRetz** [tsamsonov/grwat#5]
![2020-01-17_16-06-08](https://user-images.githubusercontent.com/25350643/72623112-9602f100-3955-11ea-9c6f-48bc297628bd.png)

**Comment by IvanDurmanov** [comment]
After recalculating in grwat package the problem was solved
![image](https://user-images.githubusercontent.com/60012070/72633215-0b2bf180-3969-11ea-80cf-cc5a1856de77.png)
